import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Image from "next/image";
import { useRouter } from "next/router";

import { useEffect, useMemo, useRef, useState } from "react";
import { GetBlogsQuery } from "@/gql/graphql";
import dayjs from "dayjs";
import { calculatePrice } from "./api/pricing_algo";

//import { insertArticles } from "@/gql/addData";

//console.log(insertArticles());

// Example usage:
/* console.log(
  calculatePrice(
    new Date("2021-11-13T09:24:00"),
    new Date("2021-11-15T15:13:00"),
    13,
    [
      {
        startDateTime: new Date("2021-11-14T12:00:00"),
        endDateTime: new Date("2021-11-14T14:01:00"),
        pricePerHour: 5,
      },
      {
        startDateTime: new Date("2021-11-15T09:00:00"),
        endDateTime: new Date("2021-11-17T00:00:00"),
        pricePerHour: 15.2,
      },
    ]
  )
); */
type BlogList = {
  author: string;
  created_at: string;
  slug: string;
  title: string;
  views: number;
  id: number;
};

type Pagination = {
  after?: string;
  before?: string;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
};

export default function Home() {
  const DEFAULT_COUNT = 10;
  const router = useRouter();
  const [blogList, setBlogList] = useState<BlogList[] | null>([]);
  const [searchVal, setSearchVal] = useState("");
  //const debounceValue = useDebounce(searchVal, 800);
  const page = useRef<string>(DEFAULT_COUNT + "");

  const [pagination, setPagination] = useState<Pagination>({
    hasNextPage: false,
    hasPreviousPage: false,
  });

  useEffect(() => {
    const urlParams = new URLSearchParams(window?.location?.search);
    const after = urlParams.get("after");
    const before = urlParams.get("before");
    const search = urlParams.get("search");
    const count = urlParams.get("count") || DEFAULT_COUNT + "";
    page.current = count;
    if (search) setSearchVal(search);
    getBlogsData(after, before, count, search);
  }, [router.asPath]);

  /* useEffect(() => {
    //route search
    if (searchVal) router.push(`/?search=${searchVal}`);
  }, [debounceValue]);
 */
  //get blogs
  const getBlogsData = (
    after?: string | null,
    before?: string | null,
    count?: string | null,
    search?: string | null
  ) => {
    setBlogList([]);

    let url = new URL(window.location.origin + "/api/getBlogs");
    let params = url.searchParams;
    if (after) params.append("after", after);
    if (before) params.append("before", before);
    if (search) params.append("search", search);
    params.append("count", count + "");
    fetch(url.toString())
      .then(async (response) => {
        const data = (await response.json()) as GetBlogsQuery;

        if (data.search_blogs_connection.edges.length != 0) {
          setBlogList(
            data.search_blogs_connection.edges.map((x) => ({
              author: x.node.author || "",
              created_at: dayjs(x.node.created_at || "").format(
                "MMMM D, YYYY, HH:MM"
              ),
              slug: x.node.slug || "",
              title: x.node.title || "",
              views: x.node.views || 0,
              id: x.node.ID,
            }))
          );
        } else {
          setBlogList(null);
        }
        setPagination({
          hasNextPage: data.search_blogs_connection.pageInfo.hasNextPage,
          hasPreviousPage:
            data.search_blogs_connection.pageInfo.hasPreviousPage,
          after: data.search_blogs_connection.pageInfo.endCursor,
          before: data.search_blogs_connection.pageInfo.startCursor,
        });
      })
      .catch((x) => {
        setBlogList([]);
        console.error(x);
      });
  };

  const getList = useMemo(() => {
    return blogList?.map((x) => (
      <li
        key={x.id}
        onClick={() => {
          router.push(`/article/${x.slug}`);
        }}
      >
        <span>
          <h2>{x.title}</h2>
          <span className={styles.blogDetails}>
            By {x.author}, {x.created_at}
          </span>
        </span>
        <span className={styles.blogView}>
          <Image
            width={30}
            height={30}
            src={"/icons/eye-solid2.svg"}
            alt="view counter"
          ></Image>
          <span className={styles.viewCount}>{x.views}</span>
        </span>
      </li>
    ));
  }, [blogList]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <header>
          <h1>Demo Blog</h1>
          <form
            onSubmit={(e) => {
              router.push(`/?search=${searchVal}`);
              e.preventDefault();
            }}
          >
            <input
              type="text"
              placeholder="Search Blog..."
              id="fname"
              name="fname"
              className="searchInput"
              value={searchVal}
              onChange={(x) => {
                console.log("HIT", x.target.value);
                setSearchVal(x.target.value);
                if (!x.target.value) router.push(`/`);
              }}
            />
            <Image
              width={30}
              height={30}
              src={"/icons/search.svg"}
              alt="view counter"
              onClick={() => {
                if (searchVal) router.push(`/?search=${searchVal}`);
              }}
            ></Image>
          </form>
        </header>
        <section>
          <ul className={styles.blogList}>
            {blogList && blogList.length > 0 && getList}
            {blogList && blogList.length == 0 && (
              <h2 className={styles.centered}>Loading...</h2>
            )}

            {blogList == null && <h2 className={styles.centered}>No Data</h2>}
          </ul>
        </section>
        <nav>
          <div
            className={!pagination.hasPreviousPage ? styles.disabled : ""}
            onClick={() => {
              if (pagination.hasPreviousPage)
                router.push(
                  `/?count=${page.current}&before=${pagination.before}` +
                    (searchVal ? `&search=${searchVal}` : ``)
                );
            }}
          >
            <Image
              width={20}
              height={20}
              src={"/icons/left-arrow.svg"}
              alt="view counter"
            ></Image>
            Prev
          </div>
          <div
            className={!pagination.hasNextPage ? styles.disabled : ""}
            onClick={() => {
              if (pagination.hasNextPage)
                router.push(
                  `/?count=${page.current}&after=${pagination.after}` +
                    (searchVal ? `&search=${searchVal}` : ``)
                );
            }}
          >
            Next{" "}
            <Image
              width={20}
              height={20}
              src={"/icons/right-arrow.svg"}
              alt="view counter"
            ></Image>
          </div>
        </nav>
      </main>
    </>
  );
}
